export enum ProjectType {
  MESYUARAT = "MESYUARAT",
  PERBINCANGAN = "PERBINCANGAN",
  KELAS = "KELAS",
}
export enum ProgressStatus {
  DRAFT = "DRAFT",
  NOT_STARTED = "NOT_STARTED",
  PLANNING = "PLANNING",
  IN_PROGRESS = "IN_PROGRESS",
  ON_HOLD = "ON_HOLD",
  UNDER_KELAS = "UNDER_KELAS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}
