export enum ProjectType {
  DISCUSSION = "DISCUSSION",
  MEETING = "MEETING",
  REVIEW = "REVIEW",
  TRAINING = "TRAINING",
  DEVELOPMENT = "DEVELOPMENT",
  RESEARCH = "RESEARCH",
  IMPLEMENTATION = "IMPLEMENTATION",
  MAINTENANCE = "MAINTENANCE",
  OTHER = "OTHER",
}
export enum ProgressStatus {
  DRAFT = "DRAFT",
  NOT_STARTED = "NOT_STARTED",
  PLANNING = "PLANNING",
  IN_PROGRESS = "IN_PROGRESS",
  ON_HOLD = "ON_HOLD",
  UNDER_REVIEW = "UNDER_REVIEW",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}
